### ISSUE TITLE
Write unit tests (75% coverage goal)

### ISSUE THREAD

**Issue by kaspar-p** [kaspar-p/busybee#2]
Tests needed for (sorted easiest to hardest):
- [x] Pure util functions (e.g. `StringInSlice`) #4 
- [ ] Entity manipulation functions (e.g. `User.ConvertUserToDocument` and `User.SortBusyTimes`); #5  
- [ ] Database (e.g. `database.DatabaseInstance.GetRoleIdsForGuilds`) #6 
- [ ] Data validity (e.g. the entire `update` package) #7 
- [ ] Ingesting new data (e.g. the entire `ingest` package) #8 
- [ ] Command Handlers (e.g. the entire `commands` package) #9

**Comment by eamonma** [comment]
The coverage goal should be higher, ideally 99.99%.
